# Generated by Django 4.2.2 on 2023-07-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="user",
        ),
    ]
